apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ob-cert
  namespace: istio-system
spec:
  secretName: ingress-cert
  commonName: ob.34.64.78.98.nip.io 
  dnsNames:
  - ob.34.64.78.98.nip.io
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
